[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["Andrew Mueller <amueller@caltech.edu>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11,<3.14"
pyinstaller = "^6.10.0"
pyserial = "^3.5"
uvicorn = "^0.30.6"
fastapi = {extras = ["standard"], version = "^0.112.2"}
pywebview = "^5.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
