[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
<<<<<<< HEAD
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.7",
    "pyserial>=3.5",
    "pywebview>=5.3.2",
=======
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.6",
    "pyinstaller>=6.11.1",
    "pyserial>=3.5",
>>>>>>> d46c6ddcac003d8b8af2b1276888fcb8d7a79f79
]
